### ISSUE TITLE
Libwally Pods are not getting installed

### ISSUE THREAD

**Issue by shantibhatt768** [Sjors/libwally-swift#55]
I had added below line into podfile

"pod 'LibWally', :git => 'https://github.com/blockchain/LibWally-Swift.git', :tag => 'v0.0.3', :submodules => true"

 and when trying to install this using "pod install" command, I am getting below error

<img width="570" alt="Screenshot 2021-12-07 at 11 17 33 AM" src="https://user-images.githubusercontent.com/93119421/144973894-0f866454-8da4-4a32-aeb0-883953c83380.png">

**Comment by Sjors** [comment]
Could you try again with the latest release (0.0.6)? https://github.com/Sjors/libwally-swift/tags

Though I think in this case you're missing build system dependencies, see those in the Build section: https://github.com/Sjors/libwally-swift#build (I should probably copy part of that to the top)

**Comment by shantibhatt768** [comment]
@Sjors, After build system dependencies, I am getting now below error

<img width="620" alt="Screenshot 2021-12-07 at 1 30 44 PM" src="https://user-images.githubusercontent.com/93119421/144989723-7d328d78-1a7e-4899-b79f-5cb464a18ecf.png">

**Comment by Sjors** [comment]
That's still the old version.

**Comment by shantibhatt768** [comment]
Tries 0.0.6 version also, same error occured


<img width="684" alt="Screenshot 2021-12-07 at 2 05 39 PM" src="https://user-images.githubusercontent.com/93119421/144994827-b04fe8f6-ce40-46cd-b941-40bc173ffff0.png">

**Comment by shantibhatt768** [comment]
Finally resolved this issue by using below commands

brew install gnu-sed automake
brew install libtool

and then "pod install"

These commands help me to integrate the library successfully
