### ISSUE TITLE
Travis replacement

### ISSUE THREAD

**Issue by Sjors** [Sjors/libwally-swift#63]
Travis builds stopped working, because afaik they no longer offer free builds for open source projects and their main product is overpriced. I'm happy to pay ~$10 per month.

I could also run a CI system on my own Ubuntu server or iMac. If anyone has recommendations (assuming this can be done securely). Maybe Apple's new Xcode SAAS can be of use? I'm really behind on these things.

**Comment by Sjors** [comment]
@jurvis any thoughts?

**Comment by jurvis** [comment]
@Sjors my iOS CI experience is also a little dated so I'm not sure I'm the person with the best information. Maybe we can try to see how far we can get with GitHub Actions? I believe build minutes for open-source repos are free :)

**Comment by jurvis** [comment]
@Sjors I can try take a look at this after I'm done with #61. since we'll probably use the new xcframework build command there anyways.
