### ISSUE TITLE
Use libwally's BIP32 path parsing code

### ISSUE THREAD

**Issue by Sjors** [Sjors/libwally-swift#65]
https://github.com/Sjors/libwally-swift/issues/64#issuecomment-1098719711

Function(s) to use:
* https://wally.readthedocs.io/en/latest/bip32/#c.bip32_key_from_parent_path_alloc

**Comment by jurvis** [comment]
@Sjors will love to give this a shot after merge work with #69 and #71. is that ok?

**Comment by Sjors** [comment]
@jurvis it's mostly implemented in #68, which could use your review (or improvements).

**Comment by jurvis** [comment]
@Sjors oh nice, didn't notice. will look at it :)
