### ISSUE TITLE
Avoid spurious rebuilding of libwally-core

### ISSUE THREAD

**Issue by Sjors** [Sjors/libwally-swift#80]
It currently rebuilds all of libwally-core every time I run a test.

**Comment by Sjors** [comment]
cc @jurvis any idea why that's happening?

**Comment by jurvis** [comment]
Ah, yes. I think the current custom build step doesn't check if the static library is already generated, and hence tries to build it every time. I'll submit a PR today or tomorrow to fix this

**Comment by jurvis** [comment]
I added changes to what you already have in `2022/11/wally-core-0.8.6` and opened #82. Let me know if it works with your workflow for nthKey? 

I need to clean up a pre-build script in the scheme, but I'll do it once you can confirm the solution works.

**Comment by Sjors** [comment]
This works great.
